build:
	@:

commit_recursively:
	bin/commit_recursively.sh

lint:
	@:

publish:
	bin/publish.sh

pull:
	bin/pull.sh

push:
	bin/push.sh

share_config:
	@:

ship:
	bin/ship.sh

switch_back_to_remote:
	@:

test:
	@:

