Makefile.cli:
	@:

build:
	@:

build_dev:
	@:

commit:
	@bin/commit.sh

lint:
	@:

publish:
	@bin/publish.sh

pull:
	@bin/pull.sh

push:
	@bin/push.sh

ship:
	@bin/ship.sh

switch_back_to_remote:
	@:

test:
	@:

update:
	@:
